version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: ".github/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/"
    groups:
      all-go-updates:
        patterns:
          - "*"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
