name: CI (Go)

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'

jobs:
  format-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # ratchet:actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # ratchet:actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Check Go Format
        run: '[ ! "$(gofmt -s -l .)" ]'

      - name: Test
        run: go test -race ./...

